const storeKey = "morrow-vanilla-tasks";
let tasks = JSON.parse(localStorage.getItem(storeKey) || "[]");
let currentList = "all", currentView = "list", editingId = null;
const $ = (id) => document.getElementById(id);
const today = () => new Date().toISOString().slice(0, 10);
const save = () => localStorage.setItem(storeKey, JSON.stringify(tasks));
const esc = (value) => String(value).replace(/[&<>'"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
function parse(text){const tags=[...text.matchAll(/#([\w-]+)/g)].map(m=>m[1].toLowerCase());const priority=(text.match(/\bp([1-4])\b/i)||[])[0]?.toLowerCase()||"";let due="";if(/\btoday\b/i.test(text))due=today();if(/\btomorrow\b/i.test(text)){const d=new Date();d.setDate(d.getDate()+1);due=d.toISOString().slice(0,10)}const title=text.replace(/#\w+/g,"").replace(/\bp[1-4]\b/ig,"").replace(/\b(today|tomorrow)\b/ig,"").trim();return{title,tags,priority,due};}
function filtered(){const search=$("search").value.toLowerCase(), status=$("status-filter").value, priority=$("priority-filter").value;return tasks.filter(t=>{if(currentList==="today"&&t.due!==today())return false;if(currentList==="upcoming"&&(!t.due||t.due<=today()||t.status==="done"))return false;if(currentList==="overdue"&&(!t.due||t.due>=today()||t.status==="done"))return false;if(currentList==="completed"&&t.status!=="done")return false;if(status&&t.status!==status)return false;if(priority&&t.priority!==priority)return false;return !search||[t.title,t.description,...t.tags].join(" ").toLowerCase().includes(search)});}
function taskHTML(t){return `<article class="task ${t.status==='done'?'done':''}" draggable="true" data-id="${t.id}"><button class="check" data-complete="${t.id}" aria-label="Complete ${esc(t.title)}">${t.status==='done'?'✓':''}</button><button class="task-info" data-edit="${t.id}"><span class="task-title">${esc(t.title)}</span><span class="meta">${t.priority?`<b class="${t.priority}">${t.priority.toUpperCase()}</b>`:''}${t.due?`<span>◷ ${t.due}</span>`:''}${t.tags.map(x=>`<span class="tag">#${esc(x)}</span>`).join('')}</span></button></article>`}
function render(){const visible=filtered(), area=$("task-area");$("all-count").textContent=tasks.length;const openToday=tasks.filter(t=>t.due===today()&&t.status!=="done").length, complete=tasks.filter(t=>t.status==='done').length;$("focus-text").textContent=`${openToday} task${openToday===1?'':'s'} remain`;$("progress-text").textContent=`${complete} of ${tasks.length} completed`;$("progress-bar").style.width=`${tasks.length?complete/tasks.length*100:0}%`;$("page-title").textContent={all:"All tasks",today:"Today",upcoming:"Upcoming",overdue:"Overdue",completed:"Completed"}[currentList];if(currentView==='board'){area.className='board';area.innerHTML=['todo','in_progress','done'].map(status=>`<section class="column" data-status="${status}"><h2>${{todo:'TO DO',in_progress:'IN PROGRESS',done:'DONE'}[status]}</h2>${visible.filter(t=>t.status===status).map(taskHTML).join('')}</section>`).join('')}else{area.className='task-list';area.innerHTML=visible.length?visible.map(taskHTML).join(''):`<div class="empty"><strong>${$("search").value?'No tasks match your search.':'Nothing here yet.'}</strong><span>Add your first task above.</span></div>`}}
function add(){const title=$("task-input").value.trim();if(!title){$("task-input").focus();return}tasks.unshift({id:crypto.randomUUID(),title,description:"",status:"todo",priority:$("priority").value,due:$("due-date").value,tags:$("tags").value.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean),created:Date.now()});save();$("task-input").value='';$("priority").value='';$("due-date").value='';$("tags").value='';render()}
function openEdit(id){const t=tasks.find(x=>x.id===id);if(!t)return;editingId=id;$("edit-title").value=t.title;$("edit-description").value=t.description;$("edit-status").value=t.status;$("edit-priority").value=t.priority;$("edit-date").value=t.due;$("edit-tags").value=t.tags.join(', ');$("task-dialog").showModal()}
$("add-button").onclick=add;$("task-input").onkeydown=e=>{if(e.key==='Enter')add()};$("parse-button").onclick=()=>{const p=parse($("task-input").value);$("task-input").value=p.title;$("priority").value=p.priority;$("due-date").value=p.due;$("tags").value=p.tags.join(', ');$("quick-details").hidden=false};$("details-toggle").onclick=()=>{$("quick-details").hidden=!$("quick-details").hidden;$("details-toggle").textContent=$("quick-details").hidden?'Add details':'Hide details'};$("search").oninput=render;$("status-filter").onchange=render;$("priority-filter").onchange=render;
document.querySelectorAll('#smart-lists button').forEach(b=>b.onclick=()=>{currentList=b.dataset.list;document.querySelectorAll('#smart-lists button').forEach(x=>x.classList.toggle('nav-active',x===b));render()});document.querySelectorAll('.view-tabs button').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;document.querySelectorAll('.view-tabs button').forEach(x=>x.classList.toggle('selected',x===b));render()});$("task-area").onclick=e=>{const target=e.target.closest('[data-complete],[data-edit]');if(!target)return;const id=target.dataset.complete||target.dataset.edit;if(target.dataset.complete){const t=tasks.find(x=>x.id===id);t.status=t.status==='done'?'todo':'done';save();render()}else openEdit(id)};$("edit-form").addEventListener('submit',e=>{e.preventDefault();const t=tasks.find(x=>x.id===editingId);Object.assign(t,{title:$("edit-title").value.trim(),description:$("edit-description").value,status:$("edit-status").value,priority:$("edit-priority").value,due:$("edit-date").value,tags:$("edit-tags").value.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean)});save();$("task-dialog").close();render()});$("delete-button").onclick=()=>{if(confirm('Delete this task?')){tasks=tasks.filter(x=>x.id!==editingId);save();$("task-dialog").close();render()}};document.addEventListener('dragstart',e=>{const card=e.target.closest('.task');if(card)e.dataTransfer.setData('text/plain',card.dataset.id)});document.addEventListener('dragover',e=>{if(e.target.closest('.column'))e.preventDefault()});document.addEventListener('drop',e=>{const column=e.target.closest('.column');if(!column)return;const t=tasks.find(x=>x.id===e.dataTransfer.getData('text/plain'));if(t){t.status=column.dataset.status;save();render()}});render();
